name: End-to-end tests
on:
  pull_request:
    branches:
      - main
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install --no-immutable

      - name: Build project
        run: yarn build

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: yarn start
          wait-on: 'http://localhost:3000'
        env:
          NEXT_PUBLIC_SUPABASE_URL: https://ixyjihpujiugurmokecq.supabase.co
          NEXT_PUBLIC_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4eWppaHB1aml1Z3VybW9rZWNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjU0NjQ2MDQsImV4cCI6MjA0MTA0MDYwNH0.Emt_TcIQ6JTMGzuwWbiOSgilD6-8JHrMaSHKJx07tUU
          NEXT_PUBLIC_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
